"""Modifier le format de date 

Revision ID: 6de43b978e9c
Revises: 13267a3c364a
Create Date: 2020-07-02 20:29:29.853481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de43b978e9c'
down_revision = '13267a3c364a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('testadd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'testadd')
    # ### end Alembic commands ###
