"""Ajout de la table auth + suppression de la colonne token dans user 

Revision ID: 863649e972c3
Revises: e6fca75f72eb
Create Date: 2020-07-02 16:58:21.796824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '863649e972c3'
down_revision = 'e6fca75f72eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
