"""Add createAt and updaeAt

Revision ID: 90f0de122058
Revises: 51b9b556ce4f
Create Date: 2020-07-02 09:31:35.077534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f0de122058'
down_revision = '51b9b556ce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['userId'], ['id'])
    op.drop_column('products', 'user_id')
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('isconnected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('lastconnecteDate', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'lastconnecteDate')
    op.drop_column('users', 'isconnected')
    op.drop_column('users', 'createdAt')
    op.add_column('products', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'users', ['user_id'], ['id'])
    op.drop_column('products', 'userId')
    op.drop_column('products', 'updatedAt')
    op.drop_column('products', 'createdAt')
    # ### end Alembic commands ###
