"""Suppression du hiredate

Revision ID: ac7563cde074
Revises: b04481642c8e
Create Date: 2020-07-02 20:55:32.499218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac7563cde074'
down_revision = 'b04481642c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'hiredate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('hiredate', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
