"""ajout du hiredate

Revision ID: b04481642c8e
Revises: feb9fb336cc8
Create Date: 2020-07-02 20:50:53.321696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04481642c8e'
down_revision = 'feb9fb336cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('hiredate', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'hiredate')
    # ### end Alembic commands ###
